"use client";

interface Campaign {
  id: string;
  brandName: string;
  headline: string;
  description: string;
  requirements: string[];
  platforms: ('TikTok' | 'Instagram' | 'YouTube Shorts')[];
  payout: string;
  payoutValue: number;
  payoutUnit: 'clip' | 'view' | 'fixed';
  deadline: string;
  deadlineDate: Date;
  spotsLeft: number;
  status: 'Open' | 'Closing Soon' | 'Completed';
  brandLogo?: string;
}

export const allAvailableCampaigns: Campaign[] = [
  {
    id: "campaign-1",
    brandName: "Glowify Skincare",
    headline: "Create a skincare reel showing morning glow results",
    description: "Glowify Skincare is looking for creators to showcase their new 'Radiant Glow Serum'. Create an authentic short-form video (TikTok) demonstrating your morning skincare routine, highlighting the serum's benefits and how it makes your skin feel. Focus on natural lighting and genuine reactions.",
    requirements: [
      "Minimum 15-second video",
      "Include #GlowifyRadiant and #SkincareRoutine",
      "Show product clearly in the video",
      "Positive and authentic tone",
      "Post within 7 days of campaign acceptance",
    ],
    platforms: ['TikTok'],
    payout: "$25 per approved clip",
    payoutValue: 25,
    payoutUnit: 'clip',
    deadline: "Nov 30, 2025",
    deadlineDate: new Date("2025-11-30"),
    spotsLeft: 12,
    status: 'Open',
  },
  {
    id: "campaign-2",
    brandName: "Nova Tech",
    headline: "Review our new smart home device on Instagram",
    description: "Nova Tech is launching its innovative 'Smart Hub Pro' and needs tech-savvy creators to provide honest reviews. Create an Instagram Reel or Story demonstrating the device's features, ease of use, and how it integrates into your smart home setup. Emphasize user experience and key functionalities.",
    requirements: [
      "Minimum 30-second video (Reel) or 3-5 stories",
      "Include #NovaSmartHub and #TechReview",
      "Demonstrate at least 3 key features",
      "Provide genuine feedback",
      "Post within 10 days of receiving product",
    ],
    platforms: ['Instagram'],
    payout: "$0.03 per view",
    payoutValue: 0.03,
    payoutUnit: 'view',
    deadline: "Dec 12, 2025",
    deadlineDate: new Date("2025-12-12"),
    spotsLeft: 5,
    status: 'Closing Soon',
  },
  {
    id: "campaign-3",
    brandName: "Blendr Energy",
    headline: "Showcase Blendr Energy drink in your workout routine",
    description: "Fuel your fitness with Blendr Energy! We're looking for energetic creators to integrate our new sugar-free energy drink into their workout or active lifestyle content. Show how Blendr gives you the boost you need to power through your day. Be creative and dynamic!",
    requirements: [
      "Minimum 20-second video",
      "Include #BlendrEnergy and #WorkoutFuel",
      "Visibly feature the Blendr Energy drink",
      "High-energy and motivating content",
      "Post within 5 days of campaign acceptance",
    ],
    platforms: ['TikTok', 'YouTube Shorts'],
    payout: "$15 per approved clip",
    payoutValue: 15,
    payoutUnit: 'clip',
    deadline: "Dec 5, 2025",
    deadlineDate: new Date("2025-12-05"),
    spotsLeft: 20,
    status: 'Open',
  },
  {
    id: "campaign-4",
    brandName: "EcoWear Apparel",
    headline: "Sustainable fashion haul for your audience",
    description: "EcoWear Apparel is committed to sustainable fashion. We want creators to highlight our latest eco-friendly collection in a fashion haul or 'get ready with me' style video. Showcase the comfort, style, and ethical production of our clothing. Inspire your audience to make conscious fashion choices.",
    requirements: [
      "Minimum 60-second video",
      "Include #EcoWearFashion and #SustainableStyle",
      "Feature at least 3 EcoWear items",
      "Discuss sustainability aspects",
      "Post within 14 days of receiving products",
    ],
    platforms: ['Instagram', 'TikTok'],
    payout: "$50 fixed fee",
    payoutValue: 50,
    payoutUnit: 'fixed',
    deadline: "Jan 15, 2026",
    deadlineDate: new Date("2026-01-15"),
    spotsLeft: 8,
    status: 'Open',
  },
  {
    id: "campaign-5",
    brandName: "GameSphere Studios",
    headline: "First look at our new indie game on YouTube Shorts",
    description: "GameSphere Studios is launching 'Pixel Quest', a retro-inspired adventure game. We're seeking gaming creators to provide a 'first look' or short gameplay highlight on YouTube Shorts. Showcase exciting moments, unique mechanics, and your initial impressions.",
    requirements: [
      "Minimum 30-second gameplay clip",
      "Include #PixelQuest and #IndieGame",
      "Showcase key gameplay features",
      "Enthusiastic and engaging commentary",
      "Post within 7 days of receiving early access code",
    ],
    platforms: ['YouTube Shorts'],
    payout: "$0.05 per view",
    payoutValue: 0.05,
    payoutUnit: 'view',
    deadline: "Dec 20, 2025",
    deadlineDate: new Date("2025-12-20"),
    spotsLeft: 15,
    status: 'Open',
  },
  {
    id: "campaign-6",
    brandName: "PetPal Treats",
    headline: "Show your pet enjoying our new healthy treats",
    description: "PetPal Treats introduces a new line of organic, healthy pet treats! We need adorable pet creators to capture their furry friends enjoying our treats. Focus on the pet's reaction, the natural ingredients, and the joy it brings. Cute and heartwarming content is key!",
    requirements: [
      "Minimum 15-second video",
      "Include #PetPalTreats and #HealthyPets",
      "Clearly show the pet enjoying the treat",
      "Highlight natural ingredients (optional voiceover)",
      "Post within 7 days of receiving treats",
    ],
    platforms: ['TikTok', 'Instagram'],
    payout: "$20 per approved clip",
    payoutValue: 20,
    payoutUnit: 'clip',
    deadline: "Nov 28, 2025",
    deadlineDate: new Date("2025-11-28"),
    spotsLeft: 3,
    status: 'Closing Soon',
  },
  {
    id: "campaign-7",
    brandName: "Urban Style Co.",
    headline: "Streetwear lookbook featuring our new collection",
    description: "Urban Style Co. is launching its fall streetwear collection. We're looking for fashion-forward creators to create a dynamic lookbook or 'outfit of the day' video. Showcase the versatility and unique design of our apparel in an urban setting.",
    requirements: [
      "Minimum 45-second video",
      "Include #UrbanStyleCo and #StreetwearFashion",
      "Feature at least 3 items from the new collection",
      "High-quality visuals and editing",
      "Post within 10 days of receiving products",
    ],
    platforms: ['Instagram', 'TikTok'],
    payout: "$60 fixed fee",
    payoutValue: 60,
    payoutUnit: 'fixed',
    deadline: "Jan 20, 2026",
    deadlineDate: new Date("2026-01-20"),
    spotsLeft: 10,
    status: 'Open',
  },
  {
    id: "campaign-8",
    brandName: "Mindful Meditations",
    headline: "Share your mindfulness journey with our new app",
    description: "Mindful Meditations is a new app designed to help users find peace and focus. We need creators to share their personal journey with mindfulness, demonstrating how the app has positively impacted their daily routine. Authentic and calming content is preferred.",
    requirements: [
      "Minimum 30-second video",
      "Include #MindfulMeditations and #WellnessJourney",
      "Showcase app interface (briefly)",
      "Speak genuinely about personal experience",
      "Post within 14 days of campaign acceptance",
    ],
    platforms: ['YouTube Shorts', 'TikTok'],
    payout: "$0.02 per view",
    payoutValue: 0.02,
    payoutUnit: 'view',
    deadline: "Feb 15, 2026",
    deadlineDate: new Date("2026-02-15"),
    spotsLeft: 7,
    status: 'Open',
  },
  {
    id: "campaign-9",
    brandName: "Gourmet Grub",
    headline: "Quick and easy recipe featuring our new sauce",
    description: "Gourmet Grub introduces a new line of artisanal sauces. We're looking for food creators to develop a quick and easy recipe video that prominently features one of our sauces. Focus on deliciousness and simplicity.",
    requirements: [
      "Minimum 60-second recipe video",
      "Include #GourmetGrub and #EasyRecipes",
      "Clearly show the sauce bottle",
      "High-quality food videography",
      "Post within 10 days of receiving product",
    ],
    platforms: ['Instagram', 'YouTube Shorts'],
    payout: "$40 per approved clip",
    payoutValue: 40,
    payoutUnit: 'clip',
    deadline: "Mar 01, 2026",
    deadlineDate: new Date("2026-03-01"),
    spotsLeft: 15,
    status: 'Open',
  },
  {
    id: "campaign-10",
    brandName: "TravelBug Adventures",
    headline: "Highlight your favorite travel destination with our gear",
    description: "TravelBug Adventures provides durable and stylish travel gear. We need adventurous creators to showcase our backpacks or accessories in a captivating video from their favorite travel destination. Emphasize functionality and aesthetic.",
    requirements: [
      "Minimum 60-second travel vlog/montage",
      "Include #TravelBugAdventures and #ExploreMore",
      "Feature at least one TravelBug product prominently",
      "Showcase beautiful scenery",
      "Post within 21 days of campaign acceptance",
    ],
    platforms: ['YouTube Shorts', 'Instagram'],
    payout: "$75 fixed fee",
    payoutValue: 75,
    payoutUnit: 'fixed',
    deadline: "Apr 05, 2026",
    deadlineDate: new Date("2026-04-05"),
    spotsLeft: 6,
    status: 'Open',
  },
  {
    id: "campaign-11",
    brandName: "HomeDecor Hub",
    headline: "DIY home decor project using our new craft supplies",
    description: "HomeDecor Hub offers unique craft supplies for DIY enthusiasts. We're seeking creative creators to demonstrate a DIY home decor project using our latest product line. Inspire your audience with innovative and achievable ideas.",
    requirements: [
      "Minimum 90-second tutorial video",
      "Include #HomeDecorHub and #DIYCrafts",
      "Clearly show the craft supplies and finished product",
      "Step-by-step instructions",
      "Post within 14 days of receiving products",
    ],
    platforms: ['TikTok', 'YouTube Shorts'],
    payout: "$35 per approved clip",
    payoutValue: 35,
    payoutUnit: 'clip',
    deadline: "May 10, 2026",
    deadlineDate: new Date("2026-05-10"),
    spotsLeft: 11,
    status: 'Open',
  },
  {
    id: "campaign-12",
    brandName: "FitnessFirst Gear",
    headline: "Showcase your intense workout with our new activewear",
    description: "FitnessFirst Gear is launching a new line of high-performance activewear. We need fitness creators to demonstrate an intense workout session while wearing our new apparel. Highlight comfort, flexibility, and style.",
    requirements: [
      "Minimum 30-second workout montage",
      "Include #FitnessFirstGear and #Activewear",
      "Feature at least one new activewear item",
      "High-energy and motivational content",
      "Post within 7 days of receiving products",
    ],
    platforms: ['Instagram', 'TikTok'],
    payout: "$0.04 per view",
    payoutValue: 0.04,
    payoutUnit: 'view',
    deadline: "Jun 15, 2026",
    deadlineDate: new Date("2026-06-15"),
    spotsLeft: 9,
    status: 'Closing Soon',
  },
];